### ISSUE TITLE
请教一个题外话

### ISSUE THREAD

**Issue by weichangdong** [fenghui2013/lua_resty_time#1]
现在lua的字符串替换函数 string.gsub（raw_str，find_str，replace_str），比如下面这种需求，
string.gsub("https://test.s3-accelerate.amazonaws.com/150779116708681.mp4","https://test.s3-accelerate.amazonaws.com",'hello')
但是不得不吧这个字符串中的点（.），（-）等等用%转义，所以能用c写一个直接替换的功能么？

**Comment by fenghui2013** [comment]
函数原型: string.gsub (s, pattern, repl [, n])
第二个参数patrern是一个正则表达式，所以个人认为使用下面的方法比较好
x = string.gsub("https://test.s3-accelerate.amazonaws.com/150779116708681.mp4","https://[%w.-]+",'hello')

希望对你有帮助

**Comment by weichangdong** [comment]
多谢回答。
我的本意是不想使用正则和不想转义。比如string.find 函数，就有一个参数表示，不使用正则。
